# Generated by Django 5.1.4 on 2025-01-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_menulink_site_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulink',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/faicon/%Y/%m/'),
        ),
    ]
