# Generated by Django 5.1.4 on 2025-01-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_menulink_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulink',
            name='favicon',
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/faicon/%Y/%m/'),
        ),
    ]
