# Generated by Django 5.1.5 on 2025-01-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_creat_at_post_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_in_post_content',
            field=models.BooleanField(default=True, help_text='If                                                 this field will marked,                                                 it will show the cover into the                                                 post.'),
        ),
    ]
