# Generated by Django 5.1.5 on 2025-01-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_postattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False, help_text='This field need                                      to be marked for the page will be shown', verbose_name='Publicar'),
        ),
    ]
